CRUD_Operation_In_MVC_Core/Controllers/FeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CRUD_Operation_In_MVC_Core.Model.Db;

namespace CRUD_Operation_In_MVC_Core.Controllers
{
    public class FeesController : Controller
    {
        private readonly mydbContext _context;

        public FeesController(mydbContext context)
        {
            _context = context;
        }

        // GET: Fees
        public async Task<IActionResult> Index()
        {
            var mydbContext = _context.Fee.Include(f => f.Student);
            return View(await mydbContext.ToListAsync());
        }

        // GET: Fees/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fee = await _context.Fee
                .Include(f => f.Student)
                .SingleOrDefaultAsync(m => m.Voucherno == id);
            if (fee == null)
            {
                return NotFound();
            }

            return View(fee);
        }

        // GET: Fees/Create
        public IActionResult Create()
        {
            ViewData["StudentId"] = new SelectList(_context.Student, "Id", "Id");
            return View();
        }

        // POST: Fees/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Voucherno,InputDate,StudentId,Headname,Amount")] Fee fee)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Add(fee);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                ViewData["StudentId"] = new SelectList(_context.Student, "Id", "Id", fee.StudentId);
                return View(fee);
            }
            catch (DbUpdateException dbx)
            {
                ViewData["err"] = "Inserted Voucher No. is already exists";
                return View();
            }
            catch (Exception ex)
            {
                ViewData["err"] = ex.Message.ToString();
                return View();
            }
        }

        // GET: Fees/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fee = await _context.Fee.SingleOrDefaultAsync(m => m.Voucherno == id);
            if (fee == null)
            {
                return NotFound();
            }
            ViewData["StudentId"] = new SelectList(_context.Student, "Id", "Id", fee.StudentId);
            return View(fee);
        }

        // POST: Fees/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Voucherno,InputDate,StudentId,Headname,Amount")] Fee fee)
        {
            if (id != fee.Voucherno)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(fee);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FeeExists(fee.Voucherno))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["StudentId"] = new SelectList(_context.Student, "Id", "Id", fee.StudentId);
            return View(fee);
        }

        // GET: Fees/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fee = await _context.Fee
                .Include(f => f.Student)
                .SingleOrDefaultAsync(m => m.Voucherno == id);
            if (fee == null)
            {
                return NotFound();
            }

            return View(fee);
        }

        // POST: Fees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var fee = await _context.Fee.SingleOrDefaultAsync(m => m.Voucherno == id);
            _context.Fee.Remove(fee);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FeeExists(string id)
        {
            return _context.Fee.Any(e => e.Voucherno == id);
        }
    }
}

CRUD_Operation_In_MVC_Core/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CRUD_Operation_In_MVC_Core.Model.Db;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace CRUD_Operation_In_MVC_Core.Controllers
{
    public class ItemsController : Controller
    {
        private readonly mydbContext _context;

        public ItemsController(mydbContext context)
        {
            _context = context;
        }

        // GET: Items
        public async Task<IActionResult> Index()
        {
            return View(await _context.Items.ToListAsync());
        }

        // GET: Items/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var items = await _context.Items
                .SingleOrDefaultAsync(m => m.Itemcode == id);
            if (items == null)
            {
                return NotFound();
            }

            return View(items);
        }

        // GET: Items/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Items/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Itemcode,Itemname,Picture")] Items items)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Add(items);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                return View(items);
            }

            catch (DbUpdateException dbx)
            {
                ViewData["err"] = "Inserted Item Code No. Is Already Exists";
                return View();
            }
            catch (Exception ex)
            {
                ViewData["err"] = ex.Message.ToString();
                return View();
            }
        }

        // GET: Items/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var items = await _context.Items.SingleOrDefaultAsync(m => m.Itemcode == id);
            if (items == null)
            {
                return NotFound();
            }
            return View(items);
        }

        // POST: Items/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Itemcode,Itemname,Picture")] Items items)
        {
            if (id != items.Itemcode)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(items);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ItemsExists(items.Itemcode))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(items);
        }

        // GET: Items/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var items = await _context.Items
                .SingleOrDefaultAsync(m => m.Itemcode == id);
            if (items == null)
            {
                return NotFound();
            }

            return View(items);
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var items = await _context.Items.SingleOrDefaultAsync(m => m.Itemcode == id);
            _context.Items.Remove(items);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ItemsExists(string id)
        {
            return _context.Items.Any(e => e.Itemcode == id);
        }

        // Uplode Files

        public ActionResult UploadFile(string id)
        {
            return View(_context.Items.Find(id));
        }
        [HttpPost, ActionName("UploadFile")]
        public ActionResult UploadFile(IFormFile file, string id)
        {
            try
            {
                if (file == null || file.Length == 0)
                    return Content("file not selected");
                if (file.Length > 0)
                {
                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images/" + file.FileName);

                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        file.CopyTo(stream);
                    }
                    Items st = (from s in _context.Items where s.Itemcode == id select s).First();
                    st.Picture = file.FileName;
                    _context.SaveChanges();
                }
                ViewBag.Message = "File Uploaded Successfully!!" + ":" + id;
                return RedirectToAction("Index");
            }
            catch
            {
                ViewBag.Message = "File upload failed!!";
                return View();
            }
        }

    }
}

CRUD_Operation_In_MVC_Core/Controllers/ItemsCrudController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace CRUD_Operation_In_MVC_Core.Controllers
{
    public class ItemsCrudController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

CRUD_Operation_In_MVC_Core/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CRUD_Operation_In_MVC_Core.Model.Db;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CRUD_Operation_In_MVC_Core.Controllers
{
    public class SearchController : Controller
    {
        private mydbContext db = new mydbContext();
        public IActionResult Index()
        {
            return View();
        }
        public ActionResult StudentExamFee()
        {
            ViewBag.studentid = new SelectList(db.Student, "id", "name");

            ViewBag.students = new List<Student>();
            ViewBag.results = new List<Examresult>();
            ViewBag.fees = new List<Fee>();
            return View();
        }
        [HttpPost, ActionName("StudentExamFee")]
        public ActionResult StudentExamFee(int studentid = 0)
        {
            try
            {
                ViewBag.studentid = new SelectList(db.Student, "id", "name");
                ViewBag.students = (from st in db.Student select new { st.Id, st.Name });
                List<Student> studentList = (from st in db.Student where st.Id == studentid select st).ToList();
                ViewBag.students = studentList;
                List<Examresult> res = (from st in db.Examresult where st.Studentid == studentid orderby st.Examsl select st).ToList();
                ViewBag.results = res;
                List<Fee> fees = (from st in db.Fee join s in db.Student on st.StudentId equals s.Id where st.StudentId == studentid orderby st.Voucherno select st).ToList();
                ViewBag.fees = fees;
                ViewBag.Message = "Post Worked";
                return View();
            }
            catch
            {
                ViewBag.Message = "File upload failed!!";
                return View();
            }
        }
    }
}

CRUD_Operation_In_MVC_Core/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CRUD_Operation_In_MVC_Core</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>




    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>



</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">CRUD_Operation_In_MVC_Core</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Items" asp-action="Index">Items</a></li>
                    <li><a asp-area="" asp-controller="Students" asp-action="Index">Students</a></li>
                    <li><a asp-area="" asp-controller="Fees" asp-action="Index">Fees</a></li>
                    <li><a asp-area="" asp-controller="ExamResults" asp-action="Index">Exam Result</a></li>
                    <li><a asp-area="" asp-controller="Search" asp-action="StudentExamFee">Search</a></li>
                    <li><a asp-area="" asp-controller="ItemsCrud" asp-action="Index">Items Crud</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - CRUD_Operation_In_MVC_Core</p>
        </footer>
    </div>

    @RenderSection("Scripts", required: false)
</body>
</html>